# Python 3.11
FROM python:3.11

# Working directory
WORKDIR /app

# requirements.txt file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# application code
COPY . .

# Set the entry point
CMD ["streamlit", "run", "analise_credito.py"]
